services:
  fastapi-app:
    # Use Docker Hub image by default, but can override with build
    image: suraj380/clearread-converter:latest
    # Uncomment the line below to build locally instead
    # build: .
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./serviceAccount.json:/app/serviceAccount.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s